version: '3.8'

services:
  appauth:
    build:
      context: .
    command: bash start-dev.sh
    ports:
      - "8087:8087"
      - "5005:5005"
    environment:
      GRADLE_USER_HOME: /box
      #SPRING_PROFILES_ACTIVE: dev
    volumes:
      - .:/authuser
      - boxauth:/box
    depends_on:
      - dbauth
    networks:
      - ead-microservices-net
  dbauth:
    image: postgres:14.5
    environment:
      POSTGRES_USER: ead-authuser
      POSTGRES_PASSWORD: ead-authuser
      POSTGRES_DB: ead-authuser
    ports:
      - "5432:5432"
    networks:
      - ead-microservices-net
  boxauth:
    image: busybox
    volumes:
      - /box
    networks:
      - ead-microservices-net
networks:
  ead-microservices-net:
    name: ead-microservices-net
    external: true
volumes:
  dbauth:
  boxauth: