server:
  port: 8087

spring:
  datasource:
    url: jdbc:postgresql://dbauth/ead-authuser
    username: ead-authuser
    password: ead-authuser

  jpa:
    hibernate:
      ddl-auto: validate
      jdbc:
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show-sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml

  output:
    ansi:
      enabled: Always

logging:
  level:
    com.ead:  TRACE
    root: INFO
    org.springframework.web:  DEBUG
    org.hibernate:  INFO

ead:
  api:
    url:
      course: 'http://appcourse:8082'